# 4.ライブラリによる分析実験(67.5/100)
# 4-1.Numpy(6:15)

## 1.NumPyの概要

配列とか行列を効率よく扱えるパッケージ。  
* **ndarray**
    * 配列用の型  
* **matrix**
    * 行列用の型    
データ型は一種類に揃える必要がある。  


## 2. NumPyでデータを扱う

In [2]:
import numpy as np

### １次元配列

In [3]:
a = np.array([1,2,3])
print(a) # 表示してみる
type(a) # オブジェクトタイプを確認してみる

[1 2 3]


numpy.ndarray

In [4]:
a.shape # 要素数を確認してみる

(3,)

### ２次元配列

In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
b.shape

(2, 3)

### 変形

In [7]:
c1 = np.array([0,1,2,3,4,5])
c1

array([0, 1, 2, 3, 4, 5])

In [8]:
c2 = c1.reshape((2,3)) # １次元の配列を２次元に変換する。要素数の数がおかしくなるとエラーが返る。
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
c3 = c2.ravel() # ２次元の配列を１次元に変換する(参照を返す）
c3

array([0, 1, 2, 3, 4, 5])

In [10]:
c4 = c2.flatten() # copyを返す
c4

array([0, 1, 2, 3, 4, 5])

### データ型(dtype)

In [11]:
a.dtype

dtype('int64')

In [12]:
d = np.array([1,2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [13]:
d.dtype

dtype('int16')

In [14]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

### インデックスとスライス

In [15]:
a

array([1, 2, 3])

In [16]:
a[0]

1

In [17]:
a[1:]

array([2, 3])

In [18]:
a[-1]

3

In [19]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b[0]

array([1, 2, 3])

In [21]:
b[1,0]

4

In [22]:
b[:,2]

array([3, 6])

In [23]:
b[1,:]

array([4, 5, 6])

In [24]:
b[0,1:]

array([2, 3])

In [25]:
b[:,[0,2]]

array([[1, 3],
       [4, 6]])

### データ再代入

In [26]:
a

array([1, 2, 3])

In [27]:
a[2] = 4
a

array([1, 2, 4])

In [28]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b[1,2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [30]:
b[:,2]=8
b

array([[1, 2, 8],
       [4, 5, 8]])

### 深いコピー(copy)

In [32]:
a1 = a
a1

array([1, 2, 4])

In [33]:
a1[1] = 5
a1

array([1, 5, 4])

In [34]:
a

array([1, 5, 4])

In [35]:
a2 = a.copy()
a2

array([1, 5, 4])

In [36]:
a2[0] = 6
a2

array([6, 5, 4])

In [37]:
a

array([1, 5, 4])

In [38]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7
c3

array([6, 1, 2, 3, 4, 5])

In [40]:
c4

array([0, 7, 2, 3, 4, 5])

In [41]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [42]:
py_list1 = [0,1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [43]:
np_array1 = np.array([0,1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


### 数列を返す(arrange)

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(4,11)

array([ 4,  5,  6,  7,  8,  9, 10])

In [48]:
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

### 乱数(random)

In [50]:
f = np.random.random((3,2))
f

array([[0.19270098, 0.72156176],
       [0.59708085, 0.28717832],
       [0.71400247, 0.15007472]])

In [51]:
np.random.seed(123)
np.random.random((3,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [54]:
np.random.seed(123)
np.random.rand(4,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [56]:
np.random.seed(123)
np.random.randint(1,10)

3

In [58]:
np.random.seed(123)
np.random.randint(1,10,(3,3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [60]:
np.random.seed(123)
np.random.uniform(0.0,5.0,size=(2,3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [61]:
np.random.seed(123)
np.random.uniform(size=(4,3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [62]:
np.random.seed(123)
np.random.randn(4,2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

### 同じ要素の数列を作る(zeros,ones)

In [63]:
np.zeros(3)

array([0., 0., 0.])

In [64]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.ones(2)

array([1., 1.])

In [66]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 単位行列(eye)

In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 指定値で埋める(full)

In [68]:
np.full(3,3.14)

array([3.14, 3.14, 3.14])

In [69]:
np.full((2,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [70]:
np.nan

nan

In [71]:
np.array([1,2,np.nan])

array([ 1.,  2., nan])

### 範囲指定で均等割データを作る(linspace)

In [72]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [74]:
np.linspace(0,np.pi,21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

### 要素間の差分(diff)

In [75]:
l = np.array([2,2,6,1,3])
np.diff(l)

array([ 0,  4, -5,  2])

###　連結(concatenate,hstack,vstack)

In [76]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [77]:
np.concatenate([a,a1])

array([1, 5, 4, 1, 5, 4])

In [78]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [79]:
b1 = np.array([[10],[20]])
b1

array([[10],
       [20]])

In [80]:
np.concatenate([b,b1],axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [81]:
np.hstack([b,b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [82]:
b2 = np.array([30,60,45])
b2

array([30, 60, 45])

In [83]:
b3 = np.vstack([b,b2])
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

### 分割(hsplit,vsplit)

In [84]:
first,second = np.hsplit(b3,[2])
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [85]:
second

array([[ 8],
       [ 8],
       [45]])

In [86]:
first1,second1 = np.vsplit(b3,[2])
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [87]:
second1

array([[30, 60, 45]])

### 転置

In [92]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [93]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

### 次元追加

In [94]:
a

array([1, 5, 4])

In [95]:
a[np.newaxis, :]

array([[1, 5, 4]])

In [96]:
a[:, np.newaxis]

array([[1],
       [5],
       [4]])

### グリッドデータの生成

In [98]:
m = np.arange(0,4)
m

array([0, 1, 2, 3])

In [99]:
n = np.arange(4,7)
n

array([4, 5, 6])

In [100]:
xx,yy = np.meshgrid(m,n)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [101]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

## 3.NumPyの各機能

In [102]:
import numpy as np
a = np.arange(3)
b = np.arange(-3,3).reshape((2,3))
c = np.arange(1,7).reshape((2,3))
d = np.arange(6).reshape((3,2))
e = np.linspace(-1,1,10)
print("a:",a)
print("b:",b)
print("c:",c)
print("d:",d)
print("e:",e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [103]:
print("a:",a.shape)
print("b:",b.shape)
print("c:",c.shape)
print("d:",d.shape)
print("e:",e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


### ユニバーサルファンクション

In [106]:
li = [[-3,-2,-1],
      [0,1,2]]
new = []
for i,j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))
new

[[3, 2, 1], [0, 1, 2]]

In [107]:
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [109]:
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [111]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [112]:
np.log(a)

/tmp/ipykernel_89/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718])

In [113]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [114]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

### ブロードキャスト

In [115]:
a

array([0, 1, 2])

In [117]:
a+10

array([10, 11, 12])

In [118]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [119]:
a+b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [120]:
a1 = a[:,np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [121]:
a+a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [122]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
c - np.mean(c)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [124]:
b * 2

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [125]:
b ** 3

array([[-27,  -8,  -1],
       [  0,   1,   8]])

In [126]:
b-a

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [127]:
a*b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [128]:
a/c

array([[0.        , 0.5       , 0.66666667],
       [0.        , 0.2       , 0.33333333]])

In [130]:
c/a

/tmp/ipykernel_89/1041459248.py:1: RuntimeWarning: divide by zero encountered in true_divide
  c/a


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

In [131]:
c/(a+1e-6)

array([[1.00000000e+06, 1.99999800e+00, 1.49999925e+00],
       [4.00000000e+06, 4.99999500e+00, 2.99999850e+00]])

### ドット積

In [132]:
np.dot(b,a)

array([-4,  5])

In [133]:
b@a

array([-4,  5])

In [134]:
b@d

array([[ -8, -14],
       [ 10,  13]])

In [135]:
d@b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

### 判定・倫理値

In [136]:
a>1

array([False, False,  True])

In [137]:
b>0

array([[False, False, False],
       [False,  True,  True]])

In [138]:
np.count_nonzero(b>0)

2

In [139]:
np.sum(b>0)

2

In [140]:
np.any(b>0)

True

In [141]:
np.all(b>0)

False

In [142]:
b[b>0]

array([1, 2])

In [143]:
b==c

array([[False, False, False],
       [False, False, False]])

In [144]:
a==b

array([[False, False, False],
       [ True,  True,  True]])

In [145]:
(b==c)|(a==b)

array([[False, False, False],
       [ True,  True,  True]])

In [146]:
b[(b==c)|(a==b)]

array([0, 1, 2])

In [147]:
np.allclose(b,c)

False

In [148]:
np.allclose(b,c,atol=10)

True

### 関数とメソッド

In [149]:
np.sum(a)

3

In [150]:
a.sum()

3

# 4-2.pandas(7:17.5)

## 1 Pandasの概要

### pandasとは

### Seriesとは

### DataFrameとは

### DataFrameの概要を見る

### インデックス名、カラム名

### データの抽出

## 2. データの読み込み・書き込み

### データ読み込み：CSVファイル

### データ読み込み：Excelファイル

### データ読み込み：WebサイトのHTMLから表を取得

### データ書き込み：CSVファイル

### データ書き込み：Excelファイル

### データの再利用

## 3.データの整形

### 使用するデータの読み込み

### 条件で抽出

### データ型変換

### 並べ替え

### 不要なカラムの削除

### 組合わせデータの挿入

## 4.時系列データ

### 1ヶ月分のデータを作る

### 1年分365日のデータを作る

### 月平均のデータにする

### 複雑な条件のインデックス

## 5.欠損値処理

## 6.データ連結

### 保存したデータを読み込み

### 列方向のデータ連結

### 行方向のデータ連結

## 7.統計データの扱い

### 保存したデータの読み込み

### 基本統計量

### 要約

### 相関係数

### 散布図行列

### データ変換


# 4-3.Matplotlib(6:15)


# 4-4.scikit-learn(8:20)
